import type { Person } from './types';

// The listed roster. Prices are in "TIME$" — TimeMarket dollars per 1-hour slot.
// Fictionalized public-figure archetypes so the market feels alive.
export const PEOPLE: Person[] = [
  {
    id: 'elon',
    ticker: 'ELON',
    name: 'Elon Mars',
    title: 'Founder · Rockets & Robots',
    sector: 'Tech',
    avatar: '🚀',
    blurb:
      'Serial founder betting the next decade on Mars, autonomy and energy. An hour now may be priceless in 2035.',
    ipoPrice: 4200,
    hoursOutstanding: 1200,
  },
  {
    id: 'oprah',
    ticker: 'OPRA',
    name: 'Opal Winfield',
    title: 'Media Mogul · Mindset',
    sector: 'Media',
    avatar: '🎤',
    blurb: 'Three decades of audience-building. A blue-chip hour with steady, defensive demand.',
    ipoPrice: 3100,
    hoursOutstanding: 900,
  },
  {
    id: 'satoshi',
    ticker: 'SATS',
    name: 'Sato Nakari',
    title: 'Anonymous Cryptographer',
    sector: 'Crypto',
    avatar: '🪙',
    blurb: 'Identity unconfirmed. Extreme volatility. The most speculative hour on the board.',
    ipoPrice: 6800,
    hoursOutstanding: 210,
  },
  {
    id: 'serena',
    ticker: 'SERN',
    name: 'Serena Vasquez',
    title: 'Athlete · 23× Champion',
    sector: 'Sports',
    avatar: '🎾',
    blurb: 'Peak-performance icon moving into ownership and venture. Strong brand floor.',
    ipoPrice: 2600,
    hoursOutstanding: 1100,
  },
  {
    id: 'curie',
    ticker: 'CURE',
    name: 'Dr. Mara Curie',
    title: 'Biotech · Longevity Lab',
    sector: 'Science',
    avatar: '🧬',
    blurb: 'Running a longevity lab with early human trials. A speculative science growth hour.',
    ipoPrice: 1900,
    hoursOutstanding: 1400,
  },
  {
    id: 'nova',
    ticker: 'NOVA',
    name: 'Nova Reyes',
    title: 'Pop Artist · 80M Listeners',
    sector: 'Music',
    avatar: '🎧',
    blurb: 'Generational fanbase, momentum trade. High volume, headline-driven swings.',
    ipoPrice: 2200,
    hoursOutstanding: 1600,
  },
  {
    id: 'graham',
    ticker: 'PGCO',
    name: 'Paul Graeme',
    title: 'Investor · Essayist',
    sector: 'Venture',
    avatar: '📈',
    blurb: 'Mentor capital. Demand from founders is inelastic — a quiet compounder.',
    ipoPrice: 3600,
    hoursOutstanding: 700,
  },
  {
    id: 'chef',
    ticker: 'GUSTO',
    name: 'Marco Gusto',
    title: 'Chef · 3 Michelin Stars',
    sector: 'Hospitality',
    avatar: '👨‍🍳',
    blurb: 'Scarcity play — books years out. Low float, sharp moves on any new opening.',
    ipoPrice: 1500,
    hoursOutstanding: 400,
  },
  {
    id: 'zen',
    ticker: 'ZEN',
    name: 'Master Anh Zen',
    title: 'Philosopher · Author',
    sector: 'Wellness',
    avatar: '🧘',
    blurb: 'Low volatility, low beta. The defensive bond-like hour of the exchange.',
    ipoPrice: 1100,
    hoursOutstanding: 2000,
  },
  {
    id: 'ada',
    ticker: 'ADA',
    name: 'Ada Lin',
    title: 'AI Researcher · AGI Lab',
    sector: 'AI',
    avatar: '🤖',
    blurb: 'Frontier-model lead. The hottest growth ticker on the board right now.',
    ipoPrice: 5400,
    hoursOutstanding: 500,
  },
  {
    id: 'rey',
    ticker: 'REY',
    name: 'Rey Montoya',
    title: 'Film Director · Auteur',
    sector: 'Media',
    avatar: '🎬',
    blurb: 'Award-season cyclical. Spikes around festivals, drifts in the off-season.',
    ipoPrice: 1700,
    hoursOutstanding: 1000,
  },
  {
    id: 'kai',
    ticker: 'KAI',
    name: 'Kai Brooks',
    title: 'Climate Founder · Fusion',
    sector: 'Energy',
    avatar: '⚡',
    blurb: 'Pre-revenue fusion moonshot. Binary outcomes, violent re-ratings on milestones.',
    ipoPrice: 2900,
    hoursOutstanding: 650,
  },
];

/** Per-person volatility (daily sigma) used by the market simulation. */
export const VOLATILITY: Record<string, number> = {
  elon: 0.05,
  oprah: 0.018,
  satoshi: 0.09,
  serena: 0.022,
  curie: 0.04,
  nova: 0.045,
  graham: 0.02,
  chef: 0.035,
  zen: 0.008,
  ada: 0.06,
  rey: 0.03,
  kai: 0.07,
};

/** Mild per-person drift so the tape isn't a pure coin flip. */
export const DRIFT: Record<string, number> = {
  elon: 0.0006,
  oprah: 0.0001,
  satoshi: 0.0,
  serena: 0.0002,
  curie: 0.0005,
  nova: 0.0003,
  graham: 0.0003,
  chef: 0.0004,
  zen: 0.0001,
  ada: 0.0009,
  rey: 0.0001,
  kai: 0.0007,
};

export const STARTING_CASH = 100_000;
